import LocationImages from "./locationimages";

const locationData = [
    {
      lat: 39.7392,
      lng: -104.9903,
      name: 'Denver, USA (Homebase)',
      date: '2020-current',
      imgs: LocationImages.denverImg,
      detail: 'This has been our home since 2020 but currently is the home to our storage unit as we travel. We moved here right before covid started and have loved it ever since. We are always looking for new places to explore in and around Colorado! ',
      arcstartlat: 39.7392,
      arcstartlng: -104.9903,
      arcendlat: 64.1470,
      arcendlng: -21.9408,
    },
    {
      lat: 64.1470,
      lng: -21.9408,
      name: 'Reykjavik, Iceland',
      date: '9 days: October 1 - 9, 2022',
      imgs: LocationImages.icelandImg,
      detail: "This was the first stop on our adventure. We rented a car, found a friend, and explored! So far, this has been Hunter's favorite place and we plan on going back! From here we flew to Scotland.",
      arcstartlat: 64.1470,
      arcstartlng: -21.9408,
      arcendlat: 55.9533,
      arcendlng: -3.1883,
    },
    {
      lat: 55.9533,
      lng: -3.1883,
      name: 'Edinburgh, Scotland',
      date: '9 days: October 9 - 19, 2022',
      imgs: LocationImages.edinburghImg,
      detail: 'We spent a week in Edinburgh and loved every minute of it. We stayed in a cute little Airbnb and explored the city. It was cocktail week, so of course that was great. This was our first taste of a castle as well! From one city to another, train ride to London.',
      paths: [
        [55.9533, -3.1883],
        [51.507222, -0.127500,]
      ],
    },
    {
      lat: 51.507222,
      lng: -0.127500,
      name: 'London, England',
      date: '2 day: October 19 - 20, 2022',
      imgs: LocationImages.londonImg,
      detail: "This was just a quick stop over to watch Marlys' favorite play, Wicked! Then flew off to Dublin for some Ireland time.",
      arcstartlat: 51.507222,
      arcstartlng: -0.127500,
      arcendlat: 52.9335,
      arcendlng: -9.3441,
    },
    {
      lat: 52.9335,
      lng: -9.3441,
      name: 'Lahinch, County Clare, Ireland',
      date: '11 days: October 20 - 30, 2022',
      imgs: LocationImages.irelandImg,
      detail: "This was our first stop in Ireland. We stayed in a great tinyhome Airbnb and explored the towns around us. We went to the Cliffs of Moher and the Burren. We totally loved the pubs with live music everywhere! And live music meant a gourp of people sitting in botths with their own instruments and just jamming away! Also, first time driving on the left side of the road! Drove back to Dublin and took a mior detour...to South Arica!",
      arcstartlat: 52.9335,
      arcstartlng: -9.3441,
      arcendlat: -26.2041,
      arcendlng: 28.0473  ,
    },
    {
      lat: -26.2041,
      lng: 28.0473,
      name: 'Johanasburg, South Africa',
      date: '5 days: October 30 - November 4, 2022',
      imgs: LocationImages.johanasburgImg,
      detail: 'Once in a lifetime trip here! We went to the safari nearish to johanasburg at Krugar National Park.  We saw just about every animal we had hoped! Even the "Big 5". This really was one of our favorite things.  After the safari we flew to Cape Town.',
      arcstartlat: -26.2041,
      arcstartlng: 28.0473,
      arcendlat: -33.9249,
      arcendlng: 18.4241,
    },
    {
      lat: -33.9249,
      lng: 18.4241,
      name: 'Capetown, South Africa',
      date: '4 days: November 4 - 8, 2022',
      imgs: LocationImages.capetownImg,
      detail: 'Cape Town was nothing short of incredible. The beaches were breathtaking, the food was tantalizing, and we even had the privilege of witnessing a Red Bull-sponsored soapbox race. It was an experience that surpassed all expectations.  After this detour, we set off for a month-long adventure in Germany.',
      arcstartlat: -33.9249,
      arcstartlng: 18.4241,
      arcendlat: 50.9375,
      arcendlng: 6.9603,
    },
    {
      lat: 50.9375,
      lng: 6.9603,
      name: 'Cologne, Germany',
      date: '33 days: November 8 - December 11, 2022',
      imgs: LocationImages.cologneImg,
      detail: "Our first long stay was a whirlwind of experiences! We enjoyed scenic train rides, stayed with a friend for a few days, and explored numerous castles, even spending a night in one that might have been haunted! The Christmas markets were a delightful addition to the festive atmosphere. While this stay wasn't our favorite due to feelings of loneliness, we walked away with a collection of unforgettable experiences. From here we hopped another train to London!",
      arcstartlat: 50.9375,
      arcstartlng: 6.9603,
      arcendlat: 51.4862,
      arcendlng: -0.9447,
    },
    {
      lat: 51.4862,
      lng: -0.9447,
      name: "London, England - Part 2",
      date: "10 days: December 11 - 21, 2022",
      imgs: LocationImages.london2Img,
      detail: "Another exciting round in London! We had a blast exploring the city with Marlys' mom and aunt, getting into the Christmas spirit along the way. Our Airbnb situation was a bit bumpy, switching three times in three days, but it didn't dampen our enthusiasm for discovering the city's treasures. Sadly, we had to leave... but we were headed to Chamonix via train!",
      paths: [
        [51.4862, -0.9447],
        [50, 2],
        [45.9434, 6.0953,]
      ],
    },
    {
      lat: 45.9434,
      lng: 6.0953,
      name: "Chamonix, France",
      date: '10 days: December 21 - 31, 2022',
      imgs: LocationImages.chamonixImg,
      detail: "Chamonix was fantastic! It was almost a taste of home with the ski town atmosphere. ☃️ We got snow, we got to snowboard in the Alps, 🏂 we got to make some new friends on top of a mountain on Christmas. 🎄 I mean, what's not to love! From here, off to Italy! First stop Venice." ,
      paths: [
        [45.9434, 6.0953],
        [45.5, 10],
        [45.4347, 12.3355],
      ],
    },
    {
      lat: 45.4347,
      lng: 12.3355,
      name: "Venice, Italy",
      date: '3 days: December 31, 2022 - January 2, 2023',
      imgs: LocationImages.veniceImg,
      detail: "Venice was a short but sweet stop. We met up with some fellow nomads while we were there and had a great time exploring the city. The shops were amazing, there was so much to see and do, and the architecture was beautiful. We were there for New Year's Eve so we got to experience the fireworks over the canals. It was an amazing sight! P.S. The canals do smell a bit, but it's not too bad. From Venice, we hopped on a train to Polignano a Mare.",
      paths: [
        [45.4347, 12.3355],
        [44, 12],
        [40.7422, 17.2157],
      ],
    },
    {
      lat: 40.7422,
      lng: 17.2157,
      name: "Polignano a Mare, Italy",
      date: '26 days: January 2 - 28, 2023',
      imgs: LocationImages.polignanoamareImg,
      detail: "Polignano a Mare was an awesome place to visit! I highly recommend it to people traveling to Italy. The only downside to our stay was that the town shuts down for a couple of months in winter, so most of the restaurants and places were closed. But there was still plenty to do and an ocean to stare at! The town was gorgeous and the train was just a 10-minute walk away, so we got a chance to explore neighboring towns and even took a weekend trip to Florence.  From here, we took a train to Rome for one more weekend in europe.",
      paths: [
        [40.7422, 17.2157],
        [41.9033, 12.4828],
      ],
    },
    {
      lat: 41.9033,
      lng: 12.4828,
      name: "Rome, Italy",
      date: '5 days: January 28 - February 1, 2023',
      imgs: LocationImages.romeImg,
      detail: "Rome was as beautiful as I had hoped. Visiting during the off-season meant shorter lines and fewer crowds, allowing us to fully immerse ourselves in the city's rich history and captivating sights. From the iconic Colosseum to the awe-inspiring Vatican City, Rome exceeded all expectations. This stay marked the end of our European adventure, as we set off to explore the vibrant cultures of Southeast Asia.",
      arcstartlat: 41.9033,
      arcstartlng: 12.4828,
      arcendlat: 3.1390,
      arcendlng: 101.6869,
    },
    {
      lat: 3.1390,
      lng: 101.6869,
      name: "Kuala Lumpur, Malaysia",
      date: '15 days: February 1 - 14, 2023',
      imgs: LocationImages.kualalumpurImg,
      detail: "KL was our first taste of SE asia and we loved it! We stayed in a great Airbnb and explored the city, the very VERY large city! So much to see here between the buildings and the Lion and Dragon dances. This was also our first time meeting up with people from Go With Less. A facebook group of people who travel like us! Our stay here was supposed to be much longer, but the GWL group was heading to Bali, so we decided to tag along.",
      arcstartlat: 3.1390,
      arcstartlng: 101.6869,
      arcendlat: -8.9,
      arcendlng: 115.1652,
    },
    {
      lat: -8.9,
      lng: 115.1652,
      name: "Bali, Indonesia",
      date: "8 days: February 14 - 22, 2023",
      imgs: LocationImages.baliImg,
      detail: "First stint in Bali!  This place what not at all what we expected. Both good and bad. The resort we stayed at was fantastic! We joined in on the free hyatt stays game and that has been a life changer.  We stayed on the eastern part of the main city in Bali in a much more chill place called Sanur. (Probably our favorite part of the island). There was so much to do in this area and so many places to eat! The GWL crew was living their best life here and we were so happy to be a part of it.  From here we flew to Bangkok for another great adventure.",
      arcstartlat: -8.9,
      arcstartlng: 115.1652,
      arcendlat: 13,
      arcendlng: 100.5018,
    },
    {
      lat: 13,
      lng: 100.5018,
      name: "Bangkok, Thailand",
      date: "4 days: February 22 - 26, 2023",
      imgs: LocationImages.bangkokImg,
      detail: "This was the start of our Cambodia tour with G-adventures.  We came to Bangkok a couple days early to explore a little but unfortunatly, one of us got the bali belly and was down for the count.  So it turned out to be a good thing that we arrived early! After a quick meet with the group, we all hopped on a bus to Cambodia!",
      paths: [
        [13, 100.5018],
        [12.9500, 103.8667],
      ],
    },
    {
      lat: 12.9500,
      lng: 103.8667,
      name: "Siem Reap, Cambodia",
      date: "7 days: February 26 - March 5, 2023",
      imgs: LocationImages.siemreapImg,
      detail: "This tour was so much fun!  And an excellent way to see Cambodia.  We started in Siem Reap and explored the temples of Angkor Wat. Which was something Hunter's always wanted to do.  There were really so many things we got to do that it's hard to list em all here. Between fourwheeling through the rice fields to walking across an island to find a hidden beach, to hanging out and getting to know our new friends! This trip really was one of the biggest highlights so far.",
      paths: [
        [12.9500, 103.8667],
        [13.5, 105],
        [10, 103.8667],
        [10.7760, 106.6917],
      ],
    },
    {
      lat: 10.7760,
      lng: 106.6917,
      name: "Ho Chi Minh City, Vietnam",
      date: "2 days: March 5 - 6, 2023",
      imgs: LocationImages.hochiminhImg,
      detail: "Sadly this was the end of the tour and we had to say bye to the group we got to know and love.  After a fun night in ho chi minh city it was off to the Philipines!",
      arcstartlat: 10.7760,
      arcstartlng: 106.6917,
      arcendlat: 15.5267,
      arcendlng: 120.0194,
    },
    {
      lat: 15.5267,
      lng: 120.0194,
      name: "Clark, Philippines",
      date: "11 days: March 6 - 17, 2023",
      imgs: LocationImages.clarkImg,
      detail: "We came here to meet up with Hunter's cousin Bodie! She was here for a few weeks for works and we decided to come say hey! The city itself wasnt the best... Kind of a dirty town with some uncomfortable relationships we got to witness... but it was fun to visit Bodie!",
      arcstartlat: 15.5267,
      arcstartlng: 120.0194,
      arcendlat: 11.9252,
      arcendlng: 119.5,
    },
    {
      lat: 11.9252,
      lng: 119.5,
      name: "El Nido, Philippines",
      date: "7 days: March 18 - 25, 2023",
      imgs: LocationImages.elnidoImg,
      detail: "This is what we wanted from the Philipines!  It had some of the best beaches we've seens so far on our travels in SE Asia!  The little town was so cool and real. And we got to rent a scooter to try that out too!  Definatly a place we would go back to! The only downside was the ride from puerto princessa to El Nido. The windy roads with a packed bus led to some unhappy travelers. They have an airport that just opened up so we would fly next time!",
      arcstartlat: 11.9252,
      arcstartlng: 119.5,
      arcendlat: 10,
      arcendlng: 120,
    },
    {
      lat: 10,
      lng: 120,
      name: "Puerto Princesa, Philippines",
      date: "7 days March 25 - 31, 2023",
      imgs: LocationImages.puertopricessaImg,
      detail: "Not a bad place, but we defintly stayed too long.  Marlys had some work calls to make, and this town had much better Internet than El Nido.  So this became our work stop before heading back to Bali.",
      arcstartlat: 10,
      arcstartlng: 120,
      arcendlat: -7.5000,
      arcendlng: 115.1652,
    },
    {
      lat: -7.5000,
      lng: 115.1652,
      name: "Canggu Bali, Indonesia",
      date: "25 days: March 31 - April 24, 2023",
      imgs: LocationImages.cangguImg,
      detail: "This was our second time getting to explore Bali and we decided to stay in a different area. (Techinically this was 3 locations, Jimbaron, Canngu, and Ubud but a majority was spent in Canngu). Canngu is the party part of Bali and it was fantastic! so many places to eat and things to see!  We also got to meet up with some peeps from the Cambodia tour! So this small tour around Bali we had friends the whole time.",
      arcstartlat: -7.5000,
      arcstartlng: 115.1652,
      arcendlat: -7.3189,
      arcendlng: 116.4072,
    },
    {
      lat: -7.3189,
      lng: 116.4072,
      name: "Gili Trawangan, Indonesia",
      date: "7 days: April 24 - May 1, 2023",
      imgs: LocationImages.gilitrawanganImg,
      detail: "Gili T and Gili M were so much fun! We absolutely recommend coming here is you visit Bali. Its a few hours by ferry, but so work it! Amazing snorkeling, great beachtime, and just a couple of cool little islands!",
      arcstartlat: -7.3189,
      arcstartlng: 116.4072,
      arcendlat: -8.6552,
      arcendlng: 116.4337,
    },
    {
      lat: -8.6552,
      lng: 116.4337,
      name: "Lombok, Indonesia",
      date: "4 days: May 1 - 4, 2023",
      imgs: LocationImages.lombokImg,
      detail: "This was just a quick stop before going back to Bali. Lombok is an island about the size of Bali nearby and so great as well! We want to come back to explore more! It's much less populated and so mountainy. So many hikes!",
      arcstartlat: -8.6552,
      arcstartlng: 116.4337,
      arcendlat: -8.3000,
      arcendlng: 114.5000,
    },
    {
      lat: -8.3000,
      lng: 114.5,
      name: "Seminyak Bali, Indonesia",
      date: "20 days: May 4 - 24, 2023",
      imgs: LocationImages.seminyakImg,
      detail: "Back to Bali! This was another great part of the island, also very partyesque. The group decided to rent a large villa for the 6 of us and it was amazing!!!!  It had a pool, with a sunken couch next to it with a small window into the pool. We dubbed the place 'Couch pool villa'. I know, super creative, but just descriptive enough! We got to visit with the otters again here! They came and played in our pool and entertained us for hours! After this short stay, we hopped back over to Sanur for some chill beach time before everyone left back to their respective countries. Except us! We were off to Bangkok to meet up with Marlys' dad (Michael) and his girlfriend (Irma)",
      arcstartlat:  -8.3000,
      arcstartlng: 114.5000,
      arcendlat: 13.8700,
      arcendlng: 100.9925,
    },
    {
      lat: 13.8700,
      lng: 100.9925,
      name: "Bangkok Thailand - Part 2",
      date: "13 days: May 24 - June 5, 2023",
      imgs: LocationImages.bangkok2Img,
      detail: "Bangkok round 2!  We got to spend some more time here to actually get to explore and had family to explore with!  But first, we had to recover because again when leaving Bali and coming to Bangkok, we had the Bali belly.... This stay was mostly a chance to recover and let Michael and Irma adjust to the jet lag before traveling around SE Asia with them.",
      arcstartlat: 13.8700,
      arcstartlng: 100.9925,
      arcendlat: 9.5869,
      arcendlng: 100.0588,
    },
    {
      lat: 9.5869,
      lng: 100.0588,
      name: "Ko Samui, Thailand",
      date: "9 days: June 5 - 13, 2023",
      imgs: LocationImages.kosamuiImg,
      detail: "Ko Samui is a small Thai island with amazing beaches and elephant rescues! It had a party vibe to it, but was calm enough beacuse this was the off season mostly.  We got to rent a car and drive around to explore the whole thing and happened upon an elephant rescue. We had such a great time on this island, I'd recommend it to anyone thinking of coming to this area.",
      arcstartlat: 9.5869,
      arcstartlng: 100.0588,
      arcendlat: 15.8346,
      arcendlng: 108.2770,
    },
    {
      lat: 15.8346,
      lng: 108.2770,
      name: "Hoi An, Vietnam",
      date: "7 days: June 13 - 19, 2023",
      imgs: LocationImages.hoianImg,
      detail: "Hoi An was a great little town! It was a bit touristy, but not too bad. This is the Vietnamese town you might have seen with all of the lanterns on display.  It felt super old school and authentic. Or as authentic as it can be.  This was also the place we had the best food so far. Simple yet delicious, the Bahn Mi Sandwiches were to die for! And Crazy cheap! Thumbs up for sure.  We also met some fun people here (Australians) and got to explore with them!",
      arcstartlat: 15.8346,
      arcstartlng: 108.2770,
      arcendlat: 1.2901,
      arcendlng: 103.8617,
    },

    {
      lat: 1.2901,
      lng: 103.8617,
      name: "Singapore",
      date: "6 days: June 19 - 24, 2023",
      imgs: LocationImages.singaporeImg,
      detail: "Singapore! It's exactly like you'd expect. Clean, modern, and expensive. We got to do all the touristy things. Like the botanical gardens and the Marina Bay Sands hotel. ",
      arcstartlat: 1.2901,
      arcstartlng: 103.8617,
      arcendlat: -8.3,
      arcendlng: 115.4715,
    },

    {
      lat: -8.3,
      lng: 115.4715,
      name: "Sanur, Bali, Indonesia",
      date: "10 days: June 24 - July 3, 2023",
      imgs: LocationImages.sanurImg,
      detail: "Bali round 3!  Back to Sanur since it's been our favorite area.  Michael and Irma got to go do all the touristy things while we stayed back. They even go to fight some monkeys! This stay marked the end of the SE Asia tour with them and we had a blast.  It was fun showing them around to all our favorite places in bali since we'd been here so much!  This was also the end of our stint in SE Asia for now as we had a wedding to attend baack in the states. But First, short trip back in Europe.",
      arcstartlat: -8.3,
      arcstartlng: 115.4715,
      arcendlat: 51.1656,
      arcendlng: 7.8,
    },
    {
      lat: 51.1656,
      lng: 7.8,
      name: "Cologne, Germany - Part 2",
      date: "3 days: July 4 - 6, 2023",
      imgs: LocationImages.cologne2Img,
      detail: "Quick stop to pick up Hunter's laptop (long painful story) then off to Barcelona for a cruise!",
      arcstartlat: 51.1656,
      arcstartlng: 7.8,
      arcendlat: 41.3833,
      arcendlng: 2.1833,
    },
    {
      lat: 41.3833,
      lng: 2.1833,
      name: "Barcelona, Spain",
      date: "4 days: July 6 - 9, 2023",
      imgs: LocationImages.barcelonaImg,
      detail: "Barcelona was great! So friendly and fun. We had a few days to explore before our cruise starts so we took advantage of that! We explored as much as we could by foot. This place was huge and had lots to see!",
      paths: [
        [41.3833, 2.1833],
        [41.3833, 5.1833],
      ],
    },
    {
      lat: 41.3833,
      lng: 5.1833,
      name: "Mediteranian Cruise",
      date: "8 days: July 9 - 16, 2023",
      imgs: LocationImages.mediteranianCruiseImg,
      detail: "Virgin Voyages Cruises! 100% recommend taking one of their cruises! It was soooooo much fun! The staff was great, the food/restaraunts were amazing, and the shows we fantastic. Not to mention the stops were awesome as well! Majorca, Mersailles, Ibiza, Cannes, and back to Barcelona. We didn't get to explore a ton beacause it was insanely hot, but we still got to see so much. Maybe best part about this cruise is that it was free! (paid for with chase points) Ended in Lisbon before heading home.",
      paths: [
        [41.3833, 2.1833],
        [39.56, 3.05],
        [43.29, 5.37],
        [43.55, 7.01],
        [38.70, 1.43],
        [41.39, 2.18],
        [38.7182, -9.1353],
      ],
    },
    {
      lat: 38.7182,
      lng: -9.1353,
      name: "Lisbon, Portugal",
      date: "2 days: July 16 - 17, 2023",
      imgs: LocationImages.lisbonImg,
      detail: "After the cruise we flew to Lisbon for a night, before heading back to the states.  We didn't get to explore a ton, but figured we'd be back.  We did get to see the famous bridge and the statue of Christ the King.  We also got to see the sunset over the city from our hotel room.  It was a great way to end our time in Europe.  From here we flew back to the states for a wedding.",
      arcstartlat: 38.7182,
      arcstartlng: -9.1353,
      arcendlat: 39.0000,
      arcendlng: -105.0007,
    },
    {
      lat: 39.0000,
      lng: -105.0007,
      name: "Denver, Colorado - Return Home",
      date: "15 days: July 17 - 31, 2023",
      imgs: LocationImages.denver2Img,
      detail: "Frist time back in so long! It was great to be back. Seeing family and friends was fantastic but the reverse culture shock was real. It wasn't too bad, but it really emphasized how different life is back here in the states.  And how great we really do have it!",
      arcstartlat: 39.0000,
      arcstartlng: -105.0007,
      arcendlat: 44.8204,
      arcendlng: -122.8994,
    }, 
    {
      lat: 44.8204,
      lng: -122.8994,
      name: "Lyons, Oregon",
      date: "8 days: July 31 - August 7, 2023",
      imgs: LocationImages.lyonsImg,
      detail: "Back to Hunter's home for a week in the summer! The best time to visit Lyons is always in the summer. The river nearby makes for a perfect hangout on those hot summer days. It was great to see the fam before heading back out and that's what this return trip was all about!",
      arcstartlat: 44.8204,
      arcstartlng: -122.8994,
      arcendlat: 33.7833,
      arcendlng: -117.8167,
    },
    {
      lat: 33.7833,
      lng: -117.8167,
      name: "Orange, California",
      date: "10 days: August 7 - 16, 2023",
      imgs: LocationImages.orangeImg,
      detail: "Next was Marlys' home for some family and friends time and of course, a wedding!  It was great to see everyone and catch up since we planned on going back out for another year! (That plan has since changed of course) After this short return to the states it was time to get back out there for more adventures!",
      arcstartlat: 33.7833,
      arcstartlng: -117.8167,
      arcendlat: 38.2464,
      arcendlng: 22.1428,
    },

   {
      lat: 38.2464,
      lng: 22.1428,
      name: "Aigio, Greece",
      date: "9 days: August 17 - 25, 2023",
      imgs: LocationImages.aigioImg,
      detail: "What a time! We came here to visit the family that invited us out while we were in Florence, Italy.  Tuens out, this is a party week for the family!  I have to admit, we couldnt keep up... between the jet lag and the late nights, we were hurting. But in a good way!  It was so cool to hang with the family and learn more about Greece on the small town side of it. And it was wild how much of the family comes back, from all around the world, to party and celebrate for 2 weeks! We got to be a part of it! So cool!",
      paths: [
        [38.2464, 22.1428],
        [37.9750, 23.7167],
      ],
    },
    {
      lat: 37.9750,
      lng: 23.7167,
      name: "Athens, Greece",
      date: "3 days: August 25 - 27, 2023",
      imgs: LocationImages.athensImg,
      detail: "Short stop in Athens (to recover from the party week!) before heading to Crete.  It was fun getting to explore, the little bit that we did, in Athens! ",
      arcstartlat: 37.9750,
      arcstartlng: 23.7167,
      arcendlat: 35.2375,
      arcendlng: 24.9458,
    },
    {
      lat: 35.2375,
      lng: 24.9458,
      name: "Crete, Greece",
      date: "8 days: August 27 - September 3, 2023",
      imgs: LocationImages.creteImg,
      detail: "Crete was such a relaxing stay! We got to stay for free at a time share location that we earned from sitting through a time share presentation in Bali.  Met a young Austrralian couple that was fun to hang with while we relaxed and recovered. (yes, still from Aigio, the family party)",
      arcstartlat: 35.2375,
      arcstartlng: 24.9458,
      arcendlat: 43.6977,
      arcendlng: 23.3219,
    },
    {
      lat: 43.6977,
      lng: 23.3219,
      name: "Sofia, Bulgaria",
      date: "3 days: September 3 - 5, 2023",
      imgs: LocationImages.sofiaImg,
      detail: "We had no idea what to expect here. And it was so much more than we could have imagined!  The best word to describe the city would be 'clean and sturdy'. Because that's exactly what it was!  It was a great stop before heading into the mountains for the next big stay!",
      paths: [
        [43.6977, 23.3219],
        [42.5000, 23.7667],
      ],
    },
    {
      lat: 42.5000,
      lng: 23.7667,
      name: "Bansko, Bulgaria",
      date: "61 days: September 5 - November 4, 2023",
      imgs: LocationImages.banskoImg,
      detail: "This place was a real taste of home! A ski town in Bulgaria was so charming and inexpensive. The digital nomad presence here was strong and we got to meet some great people. We planned on staying here for just a month, but ended up staying for 2 because we loved it so much! The hikes, the people, the town, the forests! This place was just beautiful. The only downside is that we were here in the off season, so it was a little slow.  We plan on coming back for the winter soon for snowboarding and visitng our friends we made!",
      arcstartlat: 42.5000,
      arcstartlng: 23.7667,
      arcendlat: 39.5622,
      arcendlng: 2.6775,
    },
    {
    lat: 39.5622,
    lng: 2.6775,
    name: "Majorca, Spain",
    date: "4 days: November 4 - 7, 2023",
    imgs: LocationImages.majorcaImg,
    detail: "This was just a short trip to meet up with Michael and Irma who wanted to join us for a month again! We got to explore a little bit more of the island than last time and it was fun to see it at a different time of year!",
    paths: [
      [39.5622, 2.6775],
      [38, -3.0176],
      [35.7854, -5.8601],
    ],
  },
  {
    lat: 35.7854,
    lng: -5.8601,
    name: "Tangier, Morocco",
    date: "3 days: November 7 - 9, 2023",
    imgs: LocationImages.tangierImg,
    detail: "After flying from Majorca to Sevilla, Spain we rented a car to drive to Portugal but figured since we were so close to the ferry to Morocco, we'd go check it out!  So we got to stay in Tangier for just a couple nights and had a day to explore.  We took the hop-on hop-off bus to get to see more of it in a short time.  After this short visit, we hit the road again to Carvoeiro. ",
    paths: [
      [35.7854, -5.8601],
      [37, -6.5],
      [37.0722, -8.6144],
    ],
  },
  {
    lat: 37.0722,
    lng: -8.6144,
    name: "Carvoeiro, Portugal",
    date: "23 days: November 9 - December 1, 2023",
    imgs: LocationImages.carvoeiroImg,
    detail: "What an amazing place!  We didn't really know what to expect out of Portugal this time of year, but this exceeded anything we could have imagined. This little coastal town was absolutely stunning and it quickly became a place we all want to come back to. Michael may even buy a house here!",
    arcstartlat: 37.0722,
    arcstartlng: -8.6144,
    arcendlat: 40,
    arcendlng: 12,
  },
  {
    lat: 40,
    lng: 12,
    name: "TransAltlantic Cruise out of Rome",
    date: "17 days: December 1 - 18, 2023",
    imgs: LocationImages.transAImg,
    detail: "What better way to get back home than a cruise!  This was a ton of fun.  We got to meet and hang out with soo many people. Even randomly met another couple from Denver who was on the cruise with the husbands parents.  They became our cruise comrads!  The stops were mostly places we had been before, but the final stop before heading across the Atlantic was new. The Azores! It was a tad bit rainy, but still gorgeous! Stops on this cruise: Naples, Florence, Marseille, Cadiz, Lisbon, Ponta Delgada, then finally Orlando.",
    paths: [
      [41.9028, 12.4963],
      [41., 13],
      [40.8333, 14.2500],
      [42., 11],
      [43., 11.2558],

      [43.3088, 5.3697],
      [41.3833, 2.1833],
      [37, 0],
      [36.5304, -6.2900],
      [36.5, -10],
      [38.7167, -9.1333],
      [37.7401, -25.6691],
      [28.5383, -81.3792],
    ],
  },
  {
    lat: 28.5383,
    lng: -81.3792,
    name: "Orlando, Florida",
    date: "1 days: December 18 2023",
    imgs: LocationImages.orlandoImg,
    detail: "The disembark location and flight out to denver from here.  ",
    arcstartlat: 28.5383,
    arcstartlng: -81.3792,
    arcendlat: 39,
    arcendlng: -106.5,

  },
  {
    lat: 39,
    lng: -106.5,
    name: "Denver, Colorado - Back in the States for a bit",
    date: "",
    imgs: "",
    detail: "",
    arcstartlat: "",
    arcstartlng: "",
    arcendlat: "",
    arcendlng: "",
  },
];

  export default locationData;