import LocationImages from "./locationimages";

const locationData = [
    {
      lat: 39.7392,
      lng: -104.9903,
      name: 'Denver, USA (Homebase)',
      date: '2020-current',
      imgs: LocationImages.denverImg,
      detail: 'This has been our home since 2020 but currently is the home to our storage unit as we travel. We moved here right before covid started and have loved it ever since. We are always looking for new places to explore in and around Colorado! ',
      arcstartlat: 39.7392,
      arcstartlng: -104.9903,
      arcendlat: 64.1470,
      arcendlng: -21.9408,
    },
    {
      lat: 64.1470,
      lng: -21.9408,
      name: 'Reykjavik, Iceland',
      date: '9 days: October 1 - 9, 2022',
      imgs: LocationImages.icelandImg,
      detail: "This was the first stop on our adventure. We rented a car, found a friend, and explored! So far, this has been Hunter's favorite place and we plan on going back! From here we flew to Scotland.",
      arcstartlat: 64.1470,
      arcstartlng: -21.9408,
      arcendlat: 55.9533,
      arcendlng: -3.1883,
    },
    {
      lat: 55.9533,
      lng: -3.1883,
      name: 'Edinburgh, Scotland',
      date: '9 days: October 9 - 19, 2022',
      imgs: LocationImages.edinburghImg,
      detail: 'We spent a week in Edinburgh and loved every minute of it. We stayed in a cute little Airbnb and explored the city. It was cocktail week, so of course that was great. This was our first taste of a castle as well! From one city to another, train ride to London.',
      arcstartlat: 55.9533,
      arcstartlng: -3.1883,
      arcendlat: 51.507222,
      arcendlng: -0.127500,
    },
    {
      lat: 51.507222,
      lng: -0.127500,
      name: 'London, England',
      date: '2 day: October 19 - 20, 2022',
      imgs: LocationImages.londonImg,
      detail: "This was just a quick stop over to watch Marlys' favorite play, Wicked! Then flew off to Dublin for some Ireland time.",
      arcstartlat: 51.507222,
      arcstartlng: -0.127500,
      arcendlat: 52.9335,
      arcendlng: -9.3441,
    },
    {
      lat: 52.9335,
      lng: -9.3441,
      name: 'Lahinch, County Clare, Ireland',
      date: '11 days: October 20 - 30, 2022',
      imgs: LocationImages.irelandImg,
      detail: "This was our first stop in Ireland. We stayed in a great tinyhome Airbnb and explored the towns around us. We went to the Cliffs of Moher and the Burren. We totally loved the pubs with live music everywhere! And live music meant a gourp of people sitting in botths with their own instruments and just jamming away! Also, first time driving on the left side of the road! Drove back to Dublin and took a mior detour...to South Arica!",
      arcstartlat: 52.9335,
      arcstartlng: -9.3441,
      arcendlat: -26.2041,
      arcendlng: 28.0473  ,
    },
    {
      lat: -26.2041,
      lng: 28.0473,
      name: 'Johanasburg, South Africa',
      date: '5 days: October 30 - November 4, 2022',
      imgs: LocationImages.johanasburgImg,
      detail: 'Once in a lifetime trip here! We went to the safari nearish to johanasburg at Krugar National Park.  We saw just about every animal we had hoped! Even the "Big 5". This really was one of our favorite things.  After the safari we flew to Cape Town.',
      arcstartlat: -26.2041,
      arcstartlng: 28.0473,
      arcendlat: -33.9249,
      arcendlng: 18.4241,
    },
    {
      lat: -33.9249,
      lng: 18.4241,
      name: 'Capetown, South Africa',
      date: '4 days: November 4 - 8, 2022',
      imgs: LocationImages.capetownImg,
      detail: 'Cape Town was nothing short of incredible. The beaches were breathtaking, the food was tantalizing, and we even had the privilege of witnessing a Red Bull-sponsored soapbox race. It was an experience that surpassed all expectations.  After this detour, we set off for a month-long adventure in Germany.',
      arcstartlat: -33.9249,
      arcstartlng: 18.4241,
      arcendlat: 50.9375,
      arcendlng: 6.9603,
    },
    {
      lat: 50.9375,
      lng: 6.9603,
      name: 'Cologne, Germany',
      date: '33 days: November 8 - December 11, 2022',
      imgs: LocationImages.cologneImg,
      detail: "Our first long stay was a whirlwind of experiences! We enjoyed scenic train rides, stayed with a friend for a few days, and explored numerous castles, even spending a night in one that might have been haunted! The Christmas markets were a delightful addition to the festive atmosphere. While this stay wasn't our favorite due to feelings of loneliness, we walked away with a collection of unforgettable experiences. From here we hopped another train to London!",
      arcstartlat: 50.9375,
      arcstartlng: 6.9603,
      arcendlat: 51.4862,
      arcendlng: -0.9447,
    },
    {
      lat: 51.4862,
      lng: -0.9447,
      name: "London, England - Part 2",
      date: "10 days: December 11 - 21, 2022",
      imgs: LocationImages.london2Img,
      detail: "Another exciting round in London! We had a blast exploring the city with Marlys' mom and aunt, getting into the Christmas spirit along the way. Our Airbnb situation was a bit bumpy, switching three times in three days, but it didn't dampen our enthusiasm for discovering the city's treasures. Sadly, we had to leave... but we were headed to Chamonix via train!",
      arcstartlat: 51.4862,
      arcstartlng: -0.9447,
      arcendlat: 45.9434,
      arcendlng: 6.0953,
    },
    {
      lat: 45.9434,
      lng: 6.0953,
      name: "Chamonix, France",
      date: '10 days: December 21 - 31, 2022',
      imgs: LocationImages.chamonixImg,
      detail: "Chamonix was fantastic! It was almost a taste of home with the ski town atmosphere. ☃️ We got snow, we got to snowboard in the Alps, 🏂 we got to make some new friends on top of a mountain on Christmas. 🎄 I mean, what's not to love! From here, off to Italy! First stop Venice." ,
      arcstartlat: 45.9434,
      arcstartlng: 6.0953,
      arcendlat: 45.4347,
      arcendlng: 12.3355,
    },
    {
      lat: 45.4347,
      lng: 12.3355,
      name: "Venice, Italy",
      date: '3 days: December 31, 2022 - January 2, 2023',
      imgs: LocationImages.veniceImg,
      detail: "Venice was a short but sweet stop. We met up with some fellow nomads while we were there and had a great time exploring the city. The shops were amazing, there was so much to see and do, and the architecture was beautiful. We were there for New Year's Eve so we got to experience the fireworks over the canals. It was an amazing sight! P.S. The canals do smell a bit, but it's not too bad. From Venice, we hopped on a train to Polignano a Mare.",
      arcstartlat: 45.4347,
      arcstartlng: 12.3355,
      arcendlat: 40.7422,
      arcendlng: 17.2157,
    },
    {
      lat: 40.7422,
      lng: 17.2157,
      name: "Polignano a Mare, Italy",
      date: '26 days: January 2 - 28, 2023',
      imgs: LocationImages.polignanoamareImg,
      detail: "Polignano a Mare was an awesome place to visit! I highly recommend it to people traveling to Italy. The only downside to our stay was that the town shuts down for a couple of months in winter, so most of the restaurants and places were closed. But there was still plenty to do and an ocean to stare at! The town was gorgeous and the train was just a 10-minute walk away, so we got a chance to explore neighboring towns and even took a weekend trip to Florence.  From here, we took a train to Rome for one more weekend in europe.",
      arcstartlat: 40.7422,
      arcstartlng: 17.2157,
      arcendlat: 41.9033,
      arcendlng: 12.4828,
    },
    {
      lat: 41.9033,
      lng: 12.4828,
      name: "Rome, Italy",
      date: '5 days: January 28 - February 1, 2023',
      imgs: LocationImages.romeImg,
      detail: "Rome was as beautiful as I had hoped. Visiting during the off-season meant shorter lines and fewer crowds, allowing us to fully immerse ourselves in the city's rich history and captivating sights. From the iconic Colosseum to the awe-inspiring Vatican City, Rome exceeded all expectations. This stay marked the end of our European adventure, as we set off to explore the vibrant cultures of Southeast Asia.",
      arcstartlat: 41.9033,
      arcstartlng: 12.4828,
      arcendlat: 3.1390,
      arcendlng: 101.6869,
    },
    {
      lat: 3.1390,
      lng: 101.6869,
      name: "Kuala Lumpur, Malaysia",
      date: '15 days: February 1 - 14, 2023',
      imgs: LocationImages.kualalumpurImg,
      detail: "KL was our first taste of SE asia and we loved it! We stayed in a great Airbnb and explored the city, the very VERY large city! So much to see here between the buildings and the Lion and Dragon dances. This was also our first time meeting up with people from Go With Less. A facebook group of people who travel like us! Our stay here was supposed to be much longer, but the GWL group was heading to Bali, so we decided to tag along.",
      arcstartlat: 3.1390,
      arcstartlng: 101.6869,
      arcendlat: -8.6692,
      arcendlng: 115.1652,
    },
    {
      lat: -8.7000,
      lng: 115.1652,
      name: "Bali, Indonesia",
      date: "8 days: February 14 - 22, 2023",
      imgs: LocationImages.baliImg,
      detail: "First stint in Bali!  This place what not at all what we expected. Both good and bad. The resort we stayed at was fantastic! We joined in on the free hyatt stays game and that has been a life changer.  We stayed on the eastern part of the main city in Bali in a much more chill place called Sanur. (Probably our favorite part of the island). There was so much to do in this area and so many places to eat! The GWL crew was living their best life here and we were so happy to be a part of it.  From here we flew to Bangkok for another great adventure.",
      arcstartlat: -8.6692,
      arcstartlng: 115.1652,
      arcendlat: 13.7563,
      arcendlng: 100.5018,
    },
    {
      lat: 13.7563,
      lng: 100.5018,
      name: "Bangkok, Thailand",
      date: "4 days: February 22 - 26, 2023",
      imgs: LocationImages.bangkokImg,
      detail: "This was the start of our Cambodia tour with G-adventures.  We came to Bangkok a couple days early to explore a little but unfortunatly, one of us got the bali belly and was down for the count.  So it turned out to be a good thing that we arrived early! After a quick meet with the group, we all hopped on a bus to Cambodia!",
      arcstartlat: 13.7563,
      arcstartlng: 100.5018,
      arcendlat: 12.9500,
      arcendlng: 103.8667,
    },
    {
      lat: 12.9500,
      lng: 103.8667,
      name: "Siem Reap, Cambodia",
      date: "7 days: February 26 - March 5, 2023",
      imgs: LocationImages.siemreapImg,
      detail: "This tour was so much fun!  And an excellent way to see Cambodia.  We started in Siem Reap and explored the temples of Angkor Wat. Which was something Hunter's always wanted to do.  There were really so many things we got to do that it's hard to list em all here. Between fourwheeling through the rice fields to walking across an island to find a hidden beach, to hanging out and getting to know our new friends! This trip really was one of the biggest highlights so far.",
      arcstartlat: 12.9500,
      arcstartlng: 103.8667,
      arcendlat: 10.7760,
      arcendlng: 106.6917,
    },
    {
      lat: 10.7760,
      lng: 106.6917,
      name: "Ho Chi Minh City, Vietnam",
      date: "2 days: March 5 - 6, 2023",
      imgs: LocationImages.hochiminhImg,
      detail: "Sadly this was the end of the tour and we had to say bye to the group we got to know and love.  After a fun night in ho chi minh city it was off to the Philipines!",
      arcstartlat: 10.7760,
      arcstartlng: 106.6917,
      arcendlat: 15.5267,
      arcendlng: 120.0194,
    },
    {
      lat: 15.5267,
      lng: 120.0194,
      name: "Clark, Philippines",
      date: "11 days: March 6 - 17, 2023",
      imgs: LocationImages.clarkImg,
      detail: "We came here to meet up with Hunter's cousin Bodie! She was here for a few weeks for works and we decided to come say hey! The city itself wasnt the best... Kind of a dirty town with some uncomfortable relationships we got to witness... but it was fun to visit Bodie!",
      arcstartlat: 15.5267,
      arcstartlng: 120.0194,
      arcendlat: 11.9252,
      arcendlng: 121.0316,
    },
    {
      lat: 11.9252,
      lng: 121.0316,
      name: "El Nido, Philippines",
      date: "7 days: March 18 - 25, 2023",
      imgs: LocationImages.elnidoImg,
      detail: "This is what we wanted from the Philipines!  It had some of the best beaches we've seens so far on our travels in SE Asia!  The little town was so cool and real. And we got to rent a scooter to try that out too!  Definatly a place we would go back to! The only downside was the ride from puerto princessa to El Nido. The windy roads with a packed bus led to some unhappy travelers. They have an airport that just opened up so we would fly next time!",
      arcstartlat: 11.9252,
      arcstartlng: 121.0316,
      arcendlat: 9.5295,
      arcendlng: 117.9744,
    },
    {
      lat: 9.5295,
      lng: 117.9744,
      name: "Puerto Princesa, Philippines",
      date: "7 days March 25 - 31, 2023",
      imgs: LocationImages.puertopricessaImg,
      detail: "Not a bad place, but we defintly stayed too long.  Marlys had some work calls to make, and this town had much better Internet than El Nido.  So this became our work stop before heading back to Bali.",
      arcstartlat: 9.5295,
      arcstartlng: 117.9744,
      arcendlat: -7.9000,
      arcendlng: 115.1652,
    },
    {
      lat: -7.9000,
      lng: 115.1652,
      name: "Canggu Bali, Indonesia",
      date: "",
      imgs: LocationImages.cangguImg,
      detail: "",
      arcstartlat: -7.9000,
      arcstartlng: 115.1652,
      arcendlat: -7.3189,
      arcendlng: 116.4072,
    },
    {
      lat: -7.3189,
      lng: 116.4072,
      name: "Gili Trawangan, Indonesia",
      date: "",
      imgs: LocationImages.gilitrawanganImg,
      detail: "",
      arcstartlat: -7.3189,
      arcstartlng: 116.4072,
      arcendlat: -8.6552,
      arcendlng: 116.4337,
    },
    {
      lat: -8.6552,
      lng: 116.4337,
      name: "Lombok, Indonesia",
      date: "",
      imgs: LocationImages.lombokImg,
      detail: "",
      arcstartlat: -8.6552,
      arcstartlng: 116.4337,
      arcendlat: -8.3000,
      arcendlng: 114.8000,
    },
    {
      lat: -8.3000,
      lng: 114.8000,
      name: "Seminyak Bali, Indonesia",
      date: "",
      imgs: LocationImages.seminyakImg,
      detail: "",
      arcstartlat:  -8.3000,
      arcstartlng: 114.8000,
      arcendlat: 13.8700,
      arcendlng: 100.9925,
    },
    {
      lat: 13.8700,
      lng: 100.9925,
      name: "Bangkok Thailand - Part 2",
      date: "",
      imgs: LocationImages.bangkok2Img,
      detail: "",
      arcstartlat: 13.8700,
      arcstartlng: 100.9925,
      arcendlat: 15.8346,
      arcendlng: 108.2770,
    },
    {
      lat: 15.8346,
      lng: 108.2770,
      name: "Hoi An, Vietnam",
      date: "",
      imgs: LocationImages.hoianImg,
      detail: "",
      arcstartlat: 15.8346,
      arcstartlng: 108.2770,
      arcendlat: 9.5869,
      arcendlng: 100.0588,
    },
    {
      lat: 9.5869,
      lng: 100.0588,
      name: "Ko Samui, Thailand",
      date: "",
      imgs: LocationImages.kosamuiImg,
      detail: "",
      arcstartlat: 9.5869,
      arcstartlng: 100.0588,
      arcendlat: 1.2901,
      arcendlng: 103.8617,
    },
    {
      lat: 1.2901,
      lng: 103.8617,
      name: "Singapore",
      date: "",
      imgs: LocationImages.singaporeImg,
      detail: "",
      arcstartlat: 1.2901,
      arcstartlng: 103.8617,
      arcendlat: -8.3952,
      arcendlng: 115.4715,
    },

    {
      lat: -8.3952,
      lng: 115.4715,
      name: "Sanur, Bali, Indonesia",
      date: "",
      imgs: LocationImages.sanurImg,
      detail: "",
      arcstartlat: -8.3952,
      arcstartlng: 115.4715,
      arcendlat: 51.1656,
      arcendlng: 7.4515,
    },
    {
      lat: 51.1656,
      lng: 7.4515,
      name: "Cologne, Germany - Part 2",
      date: "",
      imgs: LocationImages.cologne2Img,
      detail: "",
      arcstartlat: 51.1656,
      arcstartlng: 7.4515,
      arcendlat: 41.3833,
      arcendlng: 2.1833,
    },
    {
      lat: 41.3833,
      lng: 2.1833,
      name: "Barcelona, Spain",
      date: "",
      imgs: LocationImages.barcelonaImg,
      detail: "",
      arcstartlat: 41.3833,
      arcstartlng: 2.1833,
      arcendlat: 41.3833,
      arcendlng: 5.1833,
    },
    {
      lat: 41.3833,
      lng: 5.1833,
      name: "Mediteranian Cruise",
      date: "",
      imgs: LocationImages.mediteranianCruiseImg,
      detail: "",
      arcstartlat: 41.3833,
      arcstartlng: 5.1833,
      arcendlat: 38.7182,
      arcendlng: -9.1353,
    },
    {
      lat: 38.7182,
      lng: -9.1353,
      name: "Lisbon, Portugal",
      date: "",
      imgs: LocationImages.lisbonImg,
      detail: "",
      arcstartlat: 38.7182,
      arcstartlng: -9.1353,
      arcendlat: 39.0000,
      arcendlng: -105.0007,
    },
    {
      lat: 39.0000,
      lng: -105.0007,
      name: "Denver, Colorado - Return Home",
      date: "",
      imgs: LocationImages.denver2Img,
      detail: "",
      arcstartlat: 39.0000,
      arcstartlng: -105.0007,
      arcendlat: 44.8204,
      arcendlng: -122.8994,
    }, 
    {
      lat: 44.8204,
      lng: -122.8994,
      name: "Lyons, Oregon",
      date: "",
      imgs: LocationImages.lyonsImg,
      detail: "",
      arcstartlat: 44.8204,
      arcstartlng: -122.8994,
      arcendlat: 33.7833,
      arcendlng: -117.8167,
    },
    {
      lat: 33.7833,
      lng: -117.8167,
      name: "Orange, California",
      date: "",
      imgs: LocationImages.orangeImg,
      detail: "",
      arcstartlat: 33.7833,
      arcstartlng: -117.8167,
      arcendlat: 38.2464,
      arcendlng: 22.1428,
    },

   {
      lat: 38.2464,
      lng: 22.1428,
      name: "Aigio, Greece",
      date: "",
      imgs: LocationImages.aigioImg,
      detail: "",
      arcstartlat: 38.2464,
      arcstartlng: 22.1428,
      arcendlat: 37.9750,
      arcendlng: 23.7167,
    },
    {
      lat: 37.9750,
      lng: 23.7167,
      name: "Athens, Greece",
      date: "",
      imgs: LocationImages.athensImg,
      detail: "",
      arcstartlat: 37.9750,
      arcstartlng: 23.7167,
      arcendlat: 35.2375,
      arcendlng: 24.9458,
    },
    {
      lat: 35.2375,
      lng: 24.9458,
      name: "Crete, Greece",
      date: "",
      imgs: LocationImages.creteImg,
      detail: "",
      arcstartlat: 35.2375,
      arcstartlng: 24.9458,
      arcendlat: 43.6977,
      arcendlng: 23.3219,
    },
    {
      lat: 43.6977,
      lng: 23.3219,
      name: "Sofia, Bulgaria",
      date: "",
      imgs: LocationImages.sofiaImg,
      detail: "",
      arcstartlat: 43.6977,
      arcstartlng: 23.3219,
      arcendlat: 42.5000,
      arcendlng: 23.7667,
    },
    {
      lat: 42.5000,
      lng: 23.7667,
      name: "Bansko, Bulgaria",
      date: "",
      imgs: LocationImages.banskoImg,
      detail: "",
      arcstartlat: 42.5000,
      arcstartlng: 23.7667,
      arcendlat: 39.5622,
      arcendlng: 2.6775,
    },
    {
    lat: 39.5622,
    lng: 2.6775,
    name: "Majorca, Spain",
    date: "",
    imgs: LocationImages.majorcaImg,
    detail: "",
    arcstartlat: 39.5622,
    arcstartlng: 2.6775,
    arcendlat: 35.7854,
    arcendlng: -5.8601,
  },
  {
    lat: 35.7854,
    lng: -5.8601,
    name: "Tangier, Morocco",
    date: "",
    imgs: LocationImages.tangierImg,
    detail: "",
    arcstartlat: 35.7854,
    arcstartlng: -5.8601,
    arcendlat: 37.0722,
    arcendlng: -8.6144,
  },
  {
    lat: 37.0722,
    lng: -8.6144,
    name: "Carvoeiro, Portugal",
    date: "",
    imgs: LocationImages.carvoeiroImg,
    detail: "",
    arcstartlat: 39.5622,
    arcstartlng: 2.6775,
    arcendlat: 35.7854,
    arcendlng: -5.8601,
  },
  {
    lat: 39.5622,
    lng: 2.6775,
    name: "TransAltlantic Cruise out of Rome",
    date: "",
    imgs: LocationImages.transAImg,
    detail: "",
    arcstartlat: 39.5622,
    arcstartlng: 2.6775,
    arcendlat: 35.7854,
    arcendlng: -5.8601,
  },
  {
    lat: 39.5622,
    lng: 2.6775,
    name: "Orlando, Florida",
    date: "",
    imgs: LocationImages.orlandoImg,
    detail: "",
    arcstartlat: 39.5622,
    arcstartlng: 2.6775,
    arcendlat: 35.7854,
    arcendlng: -5.8601,
  },
];

  export default locationData;